# Generated by Django 5.0 on 2023-12-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesAPI_app', '0002_profilfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilFeedItem',
            new_name='ProfileFeedItem',
        ),
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='creatd_on',
            new_name='created_on',
        ),
    ]
